### ISSUE TITLE
Uncaught exception when the Kafka broker connection is lost. 

### ISSUE THREAD

**Issue by dhanushkad** [fwang7/node-red-contrib-kafka-node#1]
In case the Kafka, zookeeper disconnects. Following exception will occur and Node Red is crashed. 
![nodered issue](https://cloud.githubusercontent.com/assets/8362122/9267692/b13ec092-4270-11e5-8621-82c360e5283f.PNG)

**Comment by ssadams11** [comment]
Having a similar issue with a slightly different error msg

```
...
8 Oct 22:57:25 - [info] [kafka in:3518194d.cae7e6] [object Object]
{ topic: 'test',
  value: 'From cloud9',
  offset: 89,
  partition: 0,
  key: <Buffer > }
8 Oct 22:57:25 - [info] [kafka in:3518194d.cae7e6] [object Object]
{ topic: 'test',
  value: 'From cloud9',
  offset: 90,
  partition: 0,
  key: <Buffer > }
8 Oct 22:57:25 - [info] [kafka in:3518194d.cae7e6] [object Object]
{ [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }
8 Oct 22:58:37 - [red] Uncaught Exception:
8 Oct 22:58:37 - Error: connect ETIMEDOUT
  at exports._errnoException (util.js:746:11)
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1000:19)
```

**Comment by mikesparr** [comment]
Any update on this? Very similar to our scenario and we've had to resort to redeploying flows regularly to get it to reconnect.

Similar issues:
- https://github.com/SOHU-Co/kafka-node/issues/250
- https://github.com/SOHU-Co/kafka-node/issues/279
