### ISSUE TITLE
Uncaught Exception on Zookeeper connection loss

### ISSUE THREAD

**Issue by hjespers** [fwang7/node-red-contrib-kafka-node#10]
30 Aug 01:00:44 - [red] Uncaught Exception:
30 Aug 01:00:44 - CONNECTION_LOSS: Exception: CONNECTION_LOSS[-4]
    at ConnectionManager.cleanupPendingQueue (/usr/local/lib/node_modules/node-red-contrib-kafka-node/node_modules/kafka-node/node_modules/node-zookeeper-client/lib/ConnectionManager.js:189:46)
    at ConnectionManager.onSocketClosed (/usr/local/lib/node_modules/node-red-contrib-kafka-node/node_modules/kafka-node/node_modules/node-zookeeper-client/lib/ConnectionManager.js:274:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:486:12)

**Comment by mikesparr** [comment]
Any update on this? We are experiencing same thing almost daily and we have to slightly move a node in GUI, then redeploy.

Similar issues:
- https://github.com/SOHU-Co/kafka-node/issues/250
- https://github.com/SOHU-Co/kafka-node/issues/279

**Comment by hjespers** [comment]
I gave up waiting on a fix from the author of node-zookeeper-client and wrote my own node-red-contrib-rdkafka module that uses the librdkafka C/C++ library and the new Kafka 0.9/0.10 client API that doesn't require zookeeper anymore.
